#Import libraries
```{r}
pkg<-c('modelr','tidyverse')
lapply(pkg,library,character.only=TRUE)
```

#Creating sample dataset to generate the model of
```{r}
#Creating a data frame to obtain a random distribution of x and y values
#The plot the data with ggplot
dat<-tibble(
  x=runif(100,-5,5),
  y=runif(100,20,50)
)

plot<-ggplot(dat,aes(x,y))+
  geom_point()
```

#Generating models for the data
```{r}
mdl<-tibble(
  s=runif(100,-10,10),
  i=runif(100,20,50)
)

lines<-ggplot(dat,aes(x,y))+
  geom_abline(data=mdl,aes(intercept=i,slope=s),alpha=1/4)+
  geom_point()
```

#Find the general equations for the model family
```{r}
#Gives the y-values that will be generated by the model line
eqn<-function(dataset,model){
  
  for (i in length(model)){
    y=model[1][i]*dataset$x + model[2][i]
    return(y)
  }
}
```

#To find the best model of them all, emply the RMSD
```{r}
dist<-function(dataset,model){
  dataset$y-model$y
}
```


